version: '3'
services:
  asdf:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/root/.asdf/plugins/<YOUR TOOL LC>
    command: /bin/bash
    stdin_open: true
    tty: true
